#!/bin/sh

#https://git.zx2c4.com/wireguard-tools/plain/contrib/ncat-client-server/

#check hosttype
hosttype=$(puavo-conf puavo.hosttype)
case $hosttype in
    laptop|bootserver)
	break;
	;;
    *)
	sleep 999999999999999999999999999
	;;
esac
#check server
endpoint=""
ans=$(puavo-conf puavo.image.servers)
for s in $ans;do
    echo "$s" | grep -q ':872' && endpoint=$s
done
#check endpoint
if test -n "$endpoint";then
    server=$(echo "$endpoint" | xargs | cut d: -f1)
else
    sleep 999999999999999999
fi


make_module(){
    apt-get -y install wireguard-dkms
}


#ok there we go ....
server_prog="/usr/local/lib/wireguard-tools/server.sh"
client_prog="/usr/local/lib/wireguard-tools/client.sh"
case $hosttype in
    laptop)
        fping -a "$server" >/dev/null 2>&1 && $client_prog $server
    ;;
    bootserver)
	modprobe wireguard >/dev/null 2>&1 || make_module
	modprobe wireguard || { echo "no module"; sleep 999999999999999999999 }
	if brctl show link|grep -q ltsp;then
	    $server_prog &
	    sleep 1
	    ip addr flush dev ltsp
	    brctl addif ltsp wg0
	fi
    ;;    
    *)
            #should never happen	
    ;;
esac

sleep 999999999999999999999
exit 1
